### ISSUE TITLE
"Download" actions do not work in webviews

### ISSUE THREAD

**Issue by GiovanH** [sindresorhus/electron-context-menu#122]
"Download" actions pass the webview as a window to electron-dl, but electron-dl does not support webviews. Electron-dl would need to change its specification or electron-context-menu should pass the parent window instead.

**Comment by sindresorhus** [comment]
I think this should be fixed in `electron-dl`.

**Comment by GiovanH** [comment]
Is there any reason electron-context-menu shouldn't pass the parent window as suggested, at least as a stopgap measure? Perhaps along with a console warning describing the behavior.

**Comment by FormalSnake** [comment]
I will bump this, I have the same issue; here is my log when I try to save an image:

```sh
(node:3818) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'session')
    at /Users/*/Developer/formalsurf-refactor/out/main/index.js:11459:42
    at new Promise (<anonymous>)
    at download (/Users/*/Developer/formalsurf-refactor/out/main/index.js:11454:10)
    at click (/Users/*/Developer/formalsurf-refactor/out/main/index.js:11590:11)
    at MenuItem.click (node:electron/js2c/browser_init:2:34816)
    at a._executeCommand (node:electron/js2c/browser_init:2:40231)
(node:3818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```
This is how I create the context menu:
```ts
app.on("web-contents-created", (e, contents) => {
  if (contents.getType() == "webview") {
    // set context menu in webview contextMenu({ window: contents, });
    contextMenu({
      window: contents,
      prepend: (defaultActions, params, mainWindow) => [
        // Can add custom right click actions here
      ],
      showInspectElement: true,
      showSaveImageAs: true,
      showSaveImage: true,
      showCopyImageAddress: true,
      showCopyImage: true,
      showCopyVideoAddress: true,
      showSaveVideo: true,
      showSaveVideoAs: true,
    },
    );
  }
});
```

**Comment by sindresorhus** [comment]
Fixed by `electron-dl` 5, which this package now uses. Its release notes list “Fix downloads without an associated window” and “Use `session.downloadURL()` in `download()`”.

The old `Cannot read properties of undefined (reading 'session')` came from the window lookup that no longer happens. Please reopen if it still fails.
